### ISSUE TITLE
spacing issue in mobile view of website course cards. 

### ISSUE THREAD

**Issue by Abhijay007** [coding-minutes/coding-minutes.github.io#7]
In mobile view, the first three featured courses cards didn't have the required marginal space between them like the rest of the cards. 

first card  | second card  |   
:-------------------------:|:-------------------------:|
![first card](https://user-images.githubusercontent.com/64387054/137594097-bdcaae49-0287-4d2e-b3e0-4652ecad5a40.png)|![second card](https://user-images.githubusercontent.com/64387054/137594105-f69f3990-15d9-45d0-8f49-d28da2298c45.png)|

**Comment by govind030303** [comment]
Solved !!
